---
kind: pipeline
name: deploy_static_assets

clone:

steps:
  - name: prepare_package
    image: joomlaprojects/docker-images:packager
    environment:
      ssh_password:
        from_secret: ssh_password
      ssh_user:
        from_secret: ssh_user
      ssh_host:
        from_secret: ssh_host
      RINGCENTRAL_WEBHOOK:
        from_secret: notification_url
    commands:
      - mkdir build
      - cp -r -v archived.html css/ images/ img/ js/ index.html results.html robots.txt 403.html 404.html .htaccess ./build
      - rclone config create api sftp host $ssh_host user $ssh_user pass $ssh_password port 22 use_insecure_cipher true disable_hashcheck true
      - rclone copy ./build/ api:/home/api/public_html -v
      - /bin/notify

trigger:
  branch:
    - master
  event:
    - push

---
kind: pipeline
name: build_documentation

clone:

steps:
  - name: parameter_check1
    image: debian:stable-slim
    commands:
      - |
        if [ "$JTYPE" = "framework" ]; then
        exit 0
        fi
      - |
        if [ "$JTYPE" = "cms" ]; then
        exit 0
        fi
      - echo "JTYPE parameter is missing. Allowed values [framework, cms]"
      - exit 1

  - name: parameter_check2
    image: debian:stable-slim
    commands:
      - |
        if [ $JVERSION > 0 ]; then
        exit 0
        fi
      - echo 'JVERSION parameter is missing.'
      - exit 1

  - name: prepare
    image: joomlaprojects/docker-images:php7.4
    commands:
      - composer install
      - git config --global advice.detachedHead false
      - |
        if [ "$JTYPE" = "framework" ]; then
        vendor/bin/robo repos:checkout --fw=$JVERSION
        fi
      - |
        if [ "$JTYPE" = "cms" ]; then
        git clone https://github.com/joomla/joomla-cms.git ./repos/joomla-cms
        cd repos/joomla-cms
        git checkout tags/$JVERSION
        fi

  - name: generate_documentation
    image: phpdoc/phpdoc
    volumes:
      - name: phpdocumentor-cache
        path: /tmp/phpdocumentor-cache
    commands:
      - |
        if [ "$JTYPE" = "framework" ]; then 
        phpdoc -d "./repos/*/src" -t "./build/framework-$JVERSION/" --cache-folder "/tmp/phpdocumentor-cache" --template "./" --title "Joomla! Framework $JVERSION.x API" -i "./repos/string/src/phputf8" --defaultpackagename "Joomla Framework" --setting=graphs.enabled=true --setting=guides.enabled=true
        fi
      - |
        if [ "$JTYPE" = "cms" ]; then
        export MINORVERSION=${JVERSION%.*}
        export MAJORVERSION=${JVERSION:0:1}
        phpdoc -d "./repos/joomla-cms/libraries/src" -t "./build/cms-$MAJORVERSION/" --cache-folder "/tmp/phpdocumentor-cache" --template "./" --title "Joomla! CMS $MINORVERSION.x API" --defaultpackagename "Joomla CMS" --setting=graphs.enabled=true --setting=guides.enabled=true
        fi

  - name: deploy_documentation
    image: joomlaprojects/docker-images:packager
    environment:
      ssh_password:
        from_secret: ssh_password
      ssh_user:
        from_secret: ssh_user
      ssh_host:
        from_secret: ssh_host
      RINGCENTRAL_WEBHOOK:
        from_secret: notification_url
    commands:
      - rclone config create api sftp host $ssh_host user $ssh_user pass $ssh_password port 22 use_insecure_cipher true disable_hashcheck true
      - |
        if [ "$JTYPE" = "framework" ]; then
        rclone sync ./build/framework-$JVERSION/ api:/home/api/public_html/framework-$JVERSION/ -v
        fi
      - |
        if [ "$JTYPE" = "cms" ]; then
        export MINORVERSION=${JVERSION%.*}
        export MAJORVERSION=${JVERSION:0:1}
        rclone sync ./build/cms-$MAJORVERSION/ api:/home/api/public_html/cms-$MAJORVERSION/ -v
        fi
      - /bin/notify


volumes:
  - name: phpdocumentor-cache
    host:
      path: /tmp/phpdocumentor-cache

trigger:
  branch:
    - master
  event:
    - custom

---
kind: signature
hmac: 5c08c08a45e4eb39ec6e5feafd4c86d19b0843acea3ec4752e7ede4220368ffb

...
